### ISSUE TITLE
Picture doesn't display when switching from SD to HD channel

### ISSUE THREAD

**Issue by stevellion** [kiall/android-tvheadend#102]
When I switch from an SD service, to an HD service, I get sound, but no picture.
The picture remains fixed to the last frame from the SD service.
[logcat.txt](https://github.com/kiall/android-tvheadend/files/682222/logcat.txt)

**Comment by kiall** [comment]
What stream profile are you currently using? We'll try to use one called "tif" if it exists, otherwise it will fallback to TVHeadends default (which could be a per-user default, or a global default..).

It looks like your using the VLC session type, could you try with a MKV stream profile and the ExoPlayer type? We're looking to get everyone moved to that, as it's proved more reliable.

(Do note which profile your using now before changing it! Trying to workout what profiles are working for who and when etc :))

**Comment by stevellion** [comment]
I think I'm using passthrough. - All my other client devices are Rpi's runing LibreElec..

![screenshot_20170103_150436](https://cloud.githubusercontent.com/assets/839754/21611761/1d312f70-d1c6-11e6-89af-f95555dfe7b1.png)
![screenshot_20170103_150511](https://cloud.githubusercontent.com/assets/839754/21611762/1d3271c8-d1c6-11e6-9002-6314414033d7.png)

Yes, I'm using VLC. Exoplayer seemed less reliable, but I'll verify some details.

**Comment by kiall** [comment]
So, if you create a new stream profile with a name of "tif", and set it up to be a Mkv profile, ExoPlayer should perform much better.

**Comment by stevellion** [comment]
Yes, better with tif.. but if using exoplayer it shrinks the screen 3/4 to the left. (leaving right 1/4 of screen black)
VLC displays OK.

**Comment by kiall** [comment]
AH - Okay, ExoPlayer shrinking the screen to 1/4 shouldn't happen! Can you file a bug for that? In the meantime, do both HD and SD work with the tif MKV profile, but 1/4 screen?

**Comment by stevellion** [comment]
Yes, HD/SD switching works with the tif profile.
It only shrinks it by 1/4 size. 😀 
So left 3/4 has picture, right 1/4 is blank.

**Comment by stevellion** [comment]
![img_20170103_152222](https://cloud.githubusercontent.com/assets/839754/21613177/081998ec-d1cc-11e6-9f41-036ea9d15ec5.jpg) like this.

**Comment by kiall** [comment]
I don't see the problem? ;) Can you file an issue for it (better to file a new one so others searching old issues can find them as 2 different issues!). Thanks!
