### ISSUE TITLE
Playback fails after upgrade to 0.3.7

### ISSUE THREAD

**Issue by fracarvic** [kiall/android-tvheadend#165]
I was using stable channel (0.3.5) and playback was working pretty stable. After upgrade to 0.3.7 I can't watch any channel. Seems that first time I start viewing a channel is working ok, but after channel change I get video freeze and audio playing at slow speed.

After that I can't watch any channel until I reboot shield. After rebooting first channel played seems ok, but after channel change same problem.

Seems that if I disable FFmpeg audio and reboot ,video is working perfectly in all channels, but I can't get audio in lot of channels (EAC3 ...)

I fallback to 0.3.6 apk and all is working ok, the fail gets introduced for me in 0.3.7.

Im using Nvidia Shield 5.1 (Android 7.0) with tvheadend 4.1-2533.

The logs are here :
[shields-logs.txt](https://github.com/kiall/android-tvheadend/files/947947/shields-logs.txt)

**Comment by tunip** [comment]
Same issue here.

**Comment by kiall** [comment]
@tunip does going back to 0.3.6 also resolve the issue for you?

**Comment by tunip** [comment]
Yes, 0.3.6 installed and everthing is fine.

**Comment by kiall** [comment]
@tunip could you try to go back to 0.3.7 and gather some logs? I'm not seeing anything obvious in @fracarvic's, having something to compare against and find similarities may help. Thanks!

**Comment by kiall** [comment]
Q - Do either of you have the timeshift feature enabled?

**Comment by fracarvic** [comment]
I don't have timeshift enable in server or client. All app options by default.

**Comment by kiall** [comment]
Copying from G+ Post:
----------------------------
v0.3.8 has been uploaded to the stable and beta channels on Google Play, and to the GitHub releases page: https://github.com/kiall/android-tvheadend/releases

v0.3.8 removes all changes added in v0.3.7, and several users have reported v0.3.6 working fine, and v0.3.7 failing in this way. I've not been able to isolate the specific change causing this, so I decided to simply undo all changes, even if they "seemed OK" (because, they all seemed OK ;))

These changes will come back over the next little while, but won't be pushed to the stable channel on Google Play until we're confident they won't cause issues again.

**Comment by kiall** [comment]
@tunip @justinbyoung  @fracarvic since you're all seeing this, could I ask you to try a few builds for me?

First can you try: v0.3.8 should be identical to v0.3.6, except for the version number... Can you check this build works for you?

Second, can you try: v0.3.9. This build adds back some but not all of the changes from 0.3.7, I believe these are "safe".

Can you give both of these and report back? Thanks!

**Comment by fracarvic** [comment]
@kiall I upgrade to 0.3.8 from play store and works like a charm. After that I uninstall and install via adb 0.3.9 and seems that works better that 0.3.7 but fails after one or two channel changes. This time I can't get slow speed audio like 0.3.7, but when fails video doesn't show at all.

If I exit to desktop and wait some seconds, video works for first channel but fails after channel change. I submit logs.
[shields-logs2.txt.gz](https://github.com/kiall/android-tvheadend/files/952719/shields-logs2.txt.gz)

**Comment by kiall** [comment]
That's - 99% sure I see whats happening with 0.3.9 for you, will fix and build a 0.3.10 in a few minutes.

**Comment by kiall** [comment]
v0.3.10 is up on the GitHub releases page, could you give it a go? Fingers crossed ;)

**Comment by fracarvic** [comment]
Sorry to say that ... ;-) but 0.3.10, for me, works like 0.3.9. First time works, but when change channels black video. Here come new logs
[shield-logs3.txt.gz](https://github.com/kiall/android-tvheadend/files/952907/shield-logs3.txt.gz)

**Comment by kiall** [comment]
Well, 1 bug from 0.3.9 is gone... I wish I could reproduce this myself! I'm having to guess at what the issue might be ;)

The latest logs look "clean", however, I do see something relevant. One of the channel switches seems to have failed to "release" the H264 video decoder, so the next channel, assuming it's also H264, would end up with no video and only audio.

Finally - a lead.

**Comment by justinbyoung** [comment]
Just installed 0.3.10 and TVHeadend is working for me after using HaystackTV. I haven't come across any problems as of yet. I will test a bit more. Playback was failing for me on 0.3.7 after chromecasting as well so I will test that as well.

**Comment by justinbyoung** [comment]
Have been testing 0.3.10 on my Shield TV for a couple of hours, switching between live TV and other sources and haven't had any issues. Will try and test on the Mibox tomorrow.

**Comment by fracarvic** [comment]
I just installed 0.3.12 and works perfectly. All channels completely stable like 0.3.8, so seems that you have fixed the problem !!!

**Comment by kiall** [comment]
ExoPlayer and ffmpeg just got updated in v0.3.12, as well as some fixes that are likely relevant, could you guys try this release? I'm hopeful things are fixed up.

**Comment by kiall** [comment]
heh - timing and a half! Thanks @fracarvic !

**Comment by fracarvic** [comment]
Great work @kiall, Thanks !!

**Comment by kiall** [comment]
Reopen if issue are found please :)
