### ISSUE TITLE
Many DVB-EIT events have the same subtitle and summary in Tvheadend API grid

### ISSUE THREAD

**Issue by kiall** [kiall/android-tvheadend#26]
Reported on G+ here: https://plus.google.com/103039730249812922520/posts/9XHUA8XezBn

**Comment by tunip** [comment]
I expect within Live Channels to see title, episode title, description. No use or need for tvheadends summary, because in most cases it is the same as subtitle.
If you have to fill all 4 API fields in Android TV, then short and long description could be equal and filled only with tvheadend description.

Found this on android develop site about COLUMN_LONG_DESCRIPTION:
TV input services should leave this field empty if they have no additional details beyond COLUMN_SHORT_DESCRIPTION.

Then short_description is only tvheadends description.﻿

**Comment by tunip** [comment]
Instead of:
```
        // Use summary as short description, otherwise use description
        if (clientEvent.summary != null) {
            program.setShortDescription(clientEvent.summary);
        } else if (clientEvent.description != null) {
            program.setShortDescription(clientEvent.description);
        }
        // Use description as long description, otherwise use summary
        if (clientEvent.description != null) {
            program.setLongDescription(clientEvent.description);
        } else if (clientEvent.summary != null) {
            program.setLongDescription(clientEvent.summary);
        }
```

I would suggest this (if i understand the android develop guide https://developer.android.com/reference/android/media/tv/TvContract.Programs.html#COLUMN_SHORT_DESCRIPTION
https://developer.android.com/reference/android/media/tv/TvContract.Programs.html#COLUMN_LONG_DESCRIPTION):
```
        if (clientEvent.description != null) {
            program.setShortDescription(clientEvent.description);
        }
```

**Comment by tunip** [comment]
Tested my last comment and it works fine here.

Version from Play Store:
![live_channels_a](https://cloud.githubusercontent.com/assets/11404472/18599835/b967f7be-7c5a-11e6-9301-a22dd440afc0.jpg)

Version with the change from my comment:
![live_channels_b](https://cloud.githubusercontent.com/assets/11404472/18599840/c03d29e2-7c5a-11e6-90dc-9999e7a99a67.jpg)

**Comment by kiall** [comment]
The new HTSP based EPG does things this way, and is working.
