### ISSUE TITLE
Support Closed Caption

### ISSUE THREAD

**Issue by xaudiblex** [kiall/android-tvheadend#36]
Now that we are able to do pass through, would it be possible to look into closed caption support?

**Comment by kiall** [comment]
Absolutely, CC's are defiantly something we can and will support. Priority #1 right now is getting moved to HTSP, after we do, more features will start showing up :)

**Comment by kiall** [comment]
The ExoPlayer2 session type now supports subtitles, but ExoPlayer does not yet support DVBSUB format subtitles - which means a good 99% of subs this app receives won't work..

There's WIP over at https://github.com/google/ExoPlayer/pull/1781 to add support for DVBSUB to ExoPlayer, hopefully this lands soon..

**Comment by xaudiblex** [comment]
Do you happen to know if there is support for atsc US subtitles?⁣

**Comment by kiall** [comment]
@xaudiblex That depends, what codec does US ATSC use for subtitles? If you open TVHeadend, browse to Config -> DVB Inputs -> Services, find a channel with subtitles, and hit the little "i" button detailing the codecs in use.

Something like this:
![image](https://cloud.githubusercontent.com/assets/52713/21528302/7c3a312a-cd29-11e6-909d-586ce32a7b42.png)

**Comment by xaudiblex** [comment]
⁣

**Comment by kiall** [comment]
Fixed in v0.1.66 on ExoPlayer session - ExoPlayer will soon become the only session choice, and this won't be implemented on the MediaPlayer or VLC session types. If there are specific issues with this feature on ExoPlayer, using a MKV stream profile, on v0.1.66, please open a new bug.

(I'm aware DVBSUB does not work, and will open a new bug to track)
